schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "02-conveyor-belt"
owner:
  username: "ZainabM777"
  id: 321419500
  accepted_at: "2026-09-13T09:16:42Z"
source:
  owner: "dtucprog"
  owner_id: 316954301
  repo: "02-conveyor-belt"
  branch: "main"
